DOMAIN = "plex_watch"
PLATFORMS = ["sensor"]
CONF_TOKEN = "token"
CONF_SERVER_ID = "server_id"
CONF_SERVER_NAME = "server_name"
CONF_BASE_URL = "base_url"
CONF_SELECTED_SERVER = "selected_server"
CONF_USE_LOCAL = "use_local"
CONF_WATCHED_SERIES = "watched_series"
CONF_WATCHLIST_RSS_URL = "watchlist_rss_url"
CONF_TITLE_LANGUAGE = "title_language"
MAX_DASHBOARD_ITEMS = 10
DEFAULT_SCAN_INTERVAL = 30  # seconds
STORAGE_KEY = "plex_watch_storage"
STORAGE_VERSION = 1
